// <auto-generated />
using System;
using FitnessApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602211143_AddUserProfileFields")]
    partial class AddUserProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesBurned")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DurationMinutes")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessApp.Api.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("float");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("float");

                    b.Property<double>("SugarPer100g")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 165.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2736),
                            FatPer100g = 3.6000000000000001,
                            Name = "Tavuk Göğsü",
                            ProteinPer100g = 31.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 120.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2749),
                            FatPer100g = 4.0,
                            Name = "Tavuk But",
                            ProteinPer100g = 19.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 250.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2751),
                            FatPer100g = 20.0,
                            Name = "Dana Kıyma",
                            ProteinPer100g = 17.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 143.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2752),
                            FatPer100g = 3.5,
                            Name = "Dana Kuşbaşı",
                            ProteinPer100g = 26.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 114.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2753),
                            FatPer100g = 1.5,
                            Name = "Hindi Göğsü",
                            ProteinPer100g = 23.699999999999999,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 116.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2754),
                            FatPer100g = 0.80000000000000004,
                            Name = "Ton Balığı (Konserve)",
                            ProteinPer100g = 25.5,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 208.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2755),
                            FatPer100g = 13.4,
                            Name = "Somon Balığı",
                            ProteinPer100g = 20.399999999999999,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 143.0,
                            CarbsPer100g = 0.69999999999999996,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2756),
                            FatPer100g = 9.5,
                            Name = "Yumurta",
                            ProteinPer100g = 12.5,
                            SugarPer100g = 0.29999999999999999
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 61.0,
                            CarbsPer100g = 4.7999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2758),
                            FatPer100g = 3.2999999999999998,
                            Name = "Tam Yağlı Süt",
                            ProteinPer100g = 3.2000000000000002,
                            SugarPer100g = 5.0999999999999996
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 47.0,
                            CarbsPer100g = 4.7999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2759),
                            FatPer100g = 1.5,
                            Name = "Yarım Yağlı Süt",
                            ProteinPer100g = 3.2999999999999998,
                            SugarPer100g = 5.0
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 61.0,
                            CarbsPer100g = 4.7000000000000002,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2760),
                            FatPer100g = 3.2999999999999998,
                            Name = "Yoğurt",
                            ProteinPer100g = 3.5,
                            SugarPer100g = 4.7000000000000002
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 97.0,
                            CarbsPer100g = 4.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2761),
                            FatPer100g = 5.0,
                            Name = "Süzme Yoğurt",
                            ProteinPer100g = 9.0,
                            SugarPer100g = 4.0
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPer100g = 98.0,
                            CarbsPer100g = 3.3999999999999999,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2762),
                            FatPer100g = 4.2999999999999998,
                            Name = "Lor Peyniri",
                            ProteinPer100g = 11.1,
                            SugarPer100g = 2.7000000000000002
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPer100g = 264.0,
                            CarbsPer100g = 0.69999999999999996,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2763),
                            FatPer100g = 21.0,
                            Name = "Beyaz Peynir",
                            ProteinPer100g = 14.199999999999999,
                            SugarPer100g = 0.5
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPer100g = 402.0,
                            CarbsPer100g = 1.3,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2764),
                            FatPer100g = 33.100000000000001,
                            Name = "Kaşar Peyniri",
                            ProteinPer100g = 25.0,
                            SugarPer100g = 0.5
                        },
                        new
                        {
                            Id = 16,
                            CaloriesPer100g = 389.0,
                            CarbsPer100g = 66.299999999999997,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2765),
                            FatPer100g = 6.9000000000000004,
                            Name = "Yulaf Ezmesi",
                            ProteinPer100g = 16.899999999999999,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 17,
                            CaloriesPer100g = 365.0,
                            CarbsPer100g = 80.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2768),
                            FatPer100g = 0.69999999999999996,
                            Name = "Pirinç",
                            ProteinPer100g = 7.0999999999999996,
                            SugarPer100g = 0.10000000000000001
                        },
                        new
                        {
                            Id = 18,
                            CaloriesPer100g = 342.0,
                            CarbsPer100g = 75.900000000000006,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2769),
                            FatPer100g = 1.3,
                            Name = "Bulgur",
                            ProteinPer100g = 12.300000000000001,
                            SugarPer100g = 0.40000000000000002
                        },
                        new
                        {
                            Id = 19,
                            CaloriesPer100g = 371.0,
                            CarbsPer100g = 74.700000000000003,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2770),
                            FatPer100g = 1.5,
                            Name = "Makarna",
                            ProteinPer100g = 13.0,
                            SugarPer100g = 2.7000000000000002
                        },
                        new
                        {
                            Id = 20,
                            CaloriesPer100g = 77.0,
                            CarbsPer100g = 17.5,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2771),
                            FatPer100g = 0.10000000000000001,
                            Name = "Patates",
                            ProteinPer100g = 2.0,
                            SugarPer100g = 0.80000000000000004
                        },
                        new
                        {
                            Id = 21,
                            CaloriesPer100g = 86.0,
                            CarbsPer100g = 20.100000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2772),
                            FatPer100g = 0.10000000000000001,
                            Name = "Tatlı Patates",
                            ProteinPer100g = 1.6000000000000001,
                            SugarPer100g = 4.2000000000000002
                        },
                        new
                        {
                            Id = 22,
                            CaloriesPer100g = 247.0,
                            CarbsPer100g = 41.299999999999997,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2773),
                            FatPer100g = 3.3999999999999999,
                            Name = "Tam Buğday Ekmeği",
                            ProteinPer100g = 13.0,
                            SugarPer100g = 4.2999999999999998
                        },
                        new
                        {
                            Id = 23,
                            CaloriesPer100g = 266.0,
                            CarbsPer100g = 49.299999999999997,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2774),
                            FatPer100g = 3.2999999999999998,
                            Name = "Beyaz Ekmek",
                            ProteinPer100g = 8.9000000000000004,
                            SugarPer100g = 5.0
                        },
                        new
                        {
                            Id = 24,
                            CaloriesPer100g = 295.0,
                            CarbsPer100g = 55.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2775),
                            FatPer100g = 3.5,
                            Name = "Lavaş / Dürüm",
                            ProteinPer100g = 9.0,
                            SugarPer100g = 2.0
                        },
                        new
                        {
                            Id = 25,
                            CaloriesPer100g = 358.0,
                            CarbsPer100g = 63.100000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2776),
                            FatPer100g = 2.2000000000000002,
                            Name = "Kırmızı Mercimek",
                            ProteinPer100g = 23.899999999999999,
                            SugarPer100g = 2.0
                        },
                        new
                        {
                            Id = 26,
                            CaloriesPer100g = 353.0,
                            CarbsPer100g = 60.100000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2777),
                            FatPer100g = 1.1000000000000001,
                            Name = "Yeşil Mercimek",
                            ProteinPer100g = 25.800000000000001,
                            SugarPer100g = 2.0
                        },
                        new
                        {
                            Id = 27,
                            CaloriesPer100g = 364.0,
                            CarbsPer100g = 61.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2778),
                            FatPer100g = 6.0,
                            Name = "Nohut",
                            ProteinPer100g = 19.300000000000001,
                            SugarPer100g = 10.699999999999999
                        },
                        new
                        {
                            Id = 28,
                            CaloriesPer100g = 333.0,
                            CarbsPer100g = 60.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2779),
                            FatPer100g = 0.80000000000000004,
                            Name = "Kuru Fasulye",
                            ProteinPer100g = 23.600000000000001,
                            SugarPer100g = 2.1000000000000001
                        },
                        new
                        {
                            Id = 29,
                            CaloriesPer100g = 333.0,
                            CarbsPer100g = 60.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2780),
                            FatPer100g = 0.80000000000000004,
                            Name = "Barbunya",
                            ProteinPer100g = 23.600000000000001,
                            SugarPer100g = 2.2000000000000002
                        },
                        new
                        {
                            Id = 30,
                            CaloriesPer100g = 884.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2781),
                            FatPer100g = 100.0,
                            Name = "Zeytinyağı",
                            ProteinPer100g = 0.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 31,
                            CaloriesPer100g = 717.0,
                            CarbsPer100g = 0.10000000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2782),
                            FatPer100g = 81.099999999999994,
                            Name = "Tereyağı",
                            ProteinPer100g = 0.90000000000000002,
                            SugarPer100g = 0.10000000000000001
                        },
                        new
                        {
                            Id = 32,
                            CaloriesPer100g = 588.0,
                            CarbsPer100g = 20.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2783),
                            FatPer100g = 50.0,
                            Name = "Fıstık Ezmesi (Şekersiz)",
                            ProteinPer100g = 25.0,
                            SugarPer100g = 9.1999999999999993
                        },
                        new
                        {
                            Id = 33,
                            CaloriesPer100g = 579.0,
                            CarbsPer100g = 21.600000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2784),
                            FatPer100g = 49.899999999999999,
                            Name = "Badem",
                            ProteinPer100g = 21.199999999999999,
                            SugarPer100g = 4.4000000000000004
                        },
                        new
                        {
                            Id = 34,
                            CaloriesPer100g = 628.0,
                            CarbsPer100g = 16.699999999999999,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2786),
                            FatPer100g = 60.799999999999997,
                            Name = "Fındık",
                            ProteinPer100g = 15.0,
                            SugarPer100g = 4.2999999999999998
                        },
                        new
                        {
                            Id = 35,
                            CaloriesPer100g = 654.0,
                            CarbsPer100g = 13.699999999999999,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2787),
                            FatPer100g = 65.200000000000003,
                            Name = "Ceviz",
                            ProteinPer100g = 15.199999999999999,
                            SugarPer100g = 2.6000000000000001
                        },
                        new
                        {
                            Id = 36,
                            CaloriesPer100g = 585.0,
                            CarbsPer100g = 21.300000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2788),
                            FatPer100g = 49.700000000000003,
                            Name = "Kavrulmuş Yer Fıstığı",
                            ProteinPer100g = 23.699999999999999,
                            SugarPer100g = 4.9000000000000004
                        },
                        new
                        {
                            Id = 37,
                            CaloriesPer100g = 115.0,
                            CarbsPer100g = 6.2999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2789),
                            FatPer100g = 10.699999999999999,
                            Name = "Siyah Zeytin",
                            ProteinPer100g = 0.80000000000000004,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 38,
                            CaloriesPer100g = 145.0,
                            CarbsPer100g = 3.7999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2790),
                            FatPer100g = 15.300000000000001,
                            Name = "Yeşil Zeytin",
                            ProteinPer100g = 1.0,
                            SugarPer100g = 0.5
                        },
                        new
                        {
                            Id = 39,
                            CaloriesPer100g = 304.0,
                            CarbsPer100g = 82.400000000000006,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2791),
                            FatPer100g = 0.0,
                            Name = "Bal",
                            ProteinPer100g = 0.29999999999999999,
                            SugarPer100g = 82.099999999999994
                        },
                        new
                        {
                            Id = 40,
                            CaloriesPer100g = 18.0,
                            CarbsPer100g = 3.8999999999999999,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2792),
                            FatPer100g = 0.20000000000000001,
                            Name = "Domates",
                            ProteinPer100g = 0.90000000000000002,
                            SugarPer100g = 2.6000000000000001
                        },
                        new
                        {
                            Id = 41,
                            CaloriesPer100g = 15.0,
                            CarbsPer100g = 3.6000000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2793),
                            FatPer100g = 0.10000000000000001,
                            Name = "Salatalık",
                            ProteinPer100g = 0.69999999999999996,
                            SugarPer100g = 1.7
                        },
                        new
                        {
                            Id = 42,
                            CaloriesPer100g = 40.0,
                            CarbsPer100g = 9.3000000000000007,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2794),
                            FatPer100g = 0.10000000000000001,
                            Name = "Kuru Soğan",
                            ProteinPer100g = 1.1000000000000001,
                            SugarPer100g = 4.2000000000000002
                        },
                        new
                        {
                            Id = 43,
                            CaloriesPer100g = 41.0,
                            CarbsPer100g = 9.5999999999999996,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2796),
                            FatPer100g = 0.20000000000000001,
                            Name = "Havuç",
                            ProteinPer100g = 0.90000000000000002,
                            SugarPer100g = 4.7000000000000002
                        },
                        new
                        {
                            Id = 44,
                            CaloriesPer100g = 34.0,
                            CarbsPer100g = 6.5999999999999996,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2797),
                            FatPer100g = 0.40000000000000002,
                            Name = "Brokoli",
                            ProteinPer100g = 2.7999999999999998,
                            SugarPer100g = 1.7
                        },
                        new
                        {
                            Id = 45,
                            CaloriesPer100g = 23.0,
                            CarbsPer100g = 3.6000000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2798),
                            FatPer100g = 0.40000000000000002,
                            Name = "Ispanak",
                            ProteinPer100g = 2.8999999999999999,
                            SugarPer100g = 0.40000000000000002
                        },
                        new
                        {
                            Id = 46,
                            CaloriesPer100g = 89.0,
                            CarbsPer100g = 22.800000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2799),
                            FatPer100g = 0.29999999999999999,
                            Name = "Muz",
                            ProteinPer100g = 1.1000000000000001,
                            SugarPer100g = 12.199999999999999
                        },
                        new
                        {
                            Id = 47,
                            CaloriesPer100g = 52.0,
                            CarbsPer100g = 13.800000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2800),
                            FatPer100g = 0.20000000000000001,
                            Name = "Elma",
                            ProteinPer100g = 0.29999999999999999,
                            SugarPer100g = 10.4
                        },
                        new
                        {
                            Id = 48,
                            CaloriesPer100g = 47.0,
                            CarbsPer100g = 11.800000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2801),
                            FatPer100g = 0.10000000000000001,
                            Name = "Portakal",
                            ProteinPer100g = 0.90000000000000002,
                            SugarPer100g = 9.4000000000000004
                        },
                        new
                        {
                            Id = 49,
                            CaloriesPer100g = 32.0,
                            CarbsPer100g = 7.7000000000000002,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2802),
                            FatPer100g = 0.29999999999999999,
                            Name = "Çilek",
                            ProteinPer100g = 0.69999999999999996,
                            SugarPer100g = 4.9000000000000004
                        },
                        new
                        {
                            Id = 50,
                            CaloriesPer100g = 30.0,
                            CarbsPer100g = 7.5999999999999996,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2803),
                            FatPer100g = 0.20000000000000001,
                            Name = "Karpuz",
                            ProteinPer100g = 0.59999999999999998,
                            SugarPer100g = 6.2000000000000002
                        },
                        new
                        {
                            Id = 51,
                            CaloriesPer100g = 250.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2854),
                            FatPer100g = 14.0,
                            Name = "Pastırma (Çemensiz)",
                            ProteinPer100g = 30.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 52,
                            CaloriesPer100g = 135.0,
                            CarbsPer100g = 4.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2856),
                            FatPer100g = 4.0,
                            Name = "Dana Ciğer",
                            ProteinPer100g = 20.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 53,
                            CaloriesPer100g = 200.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2857),
                            FatPer100g = 15.0,
                            Name = "Tavuk Kanat (Derili)",
                            ProteinPer100g = 18.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 54,
                            CaloriesPer100g = 131.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2858),
                            FatPer100g = 5.0,
                            Name = "Hamsi",
                            ProteinPer100g = 20.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 55,
                            CaloriesPer100g = 97.0,
                            CarbsPer100g = 0.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2859),
                            FatPer100g = 2.0,
                            Name = "Levrek",
                            ProteinPer100g = 18.0,
                            SugarPer100g = 0.0
                        },
                        new
                        {
                            Id = 56,
                            CaloriesPer100g = 43.0,
                            CarbsPer100g = 4.7999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2860),
                            FatPer100g = 1.0,
                            Name = "Kefir",
                            ProteinPer100g = 3.2999999999999998,
                            SugarPer100g = 4.7999999999999998
                        },
                        new
                        {
                            Id = 57,
                            CaloriesPer100g = 85.0,
                            CarbsPer100g = 2.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2861),
                            FatPer100g = 1.0,
                            Name = "Çökelek",
                            ProteinPer100g = 14.0,
                            SugarPer100g = 1.5
                        },
                        new
                        {
                            Id = 58,
                            CaloriesPer100g = 250.0,
                            CarbsPer100g = 1.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2863),
                            FatPer100g = 18.0,
                            Name = "Dil Peyniri",
                            ProteinPer100g = 20.0,
                            SugarPer100g = 1.0
                        },
                        new
                        {
                            Id = 59,
                            CaloriesPer100g = 320.0,
                            CarbsPer100g = 2.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2864),
                            FatPer100g = 25.0,
                            Name = "Hellim Peyniri",
                            ProteinPer100g = 22.0,
                            SugarPer100g = 1.0
                        },
                        new
                        {
                            Id = 60,
                            CaloriesPer100g = 350.0,
                            CarbsPer100g = 2.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2865),
                            FatPer100g = 27.0,
                            Name = "Tulum Peyniri",
                            ProteinPer100g = 25.0,
                            SugarPer100g = 1.0
                        },
                        new
                        {
                            Id = 61,
                            CaloriesPer100g = 275.0,
                            CarbsPer100g = 55.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2866),
                            FatPer100g = 2.0,
                            Name = "Simit",
                            ProteinPer100g = 9.0,
                            SugarPer100g = 5.0
                        },
                        new
                        {
                            Id = 62,
                            CaloriesPer100g = 220.0,
                            CarbsPer100g = 40.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2867),
                            FatPer100g = 3.0,
                            Name = "Kepek Ekmeği",
                            ProteinPer100g = 9.0,
                            SugarPer100g = 3.0
                        },
                        new
                        {
                            Id = 63,
                            CaloriesPer100g = 259.0,
                            CarbsPer100g = 48.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2868),
                            FatPer100g = 3.0,
                            Name = "Çavdar Ekmeği",
                            ProteinPer100g = 9.0,
                            SugarPer100g = 3.0
                        },
                        new
                        {
                            Id = 64,
                            CaloriesPer100g = 400.0,
                            CarbsPer100g = 75.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2869),
                            FatPer100g = 5.0,
                            Name = "Galeta (Sade)",
                            ProteinPer100g = 11.0,
                            SugarPer100g = 2.0
                        },
                        new
                        {
                            Id = 65,
                            CaloriesPer100g = 280.0,
                            CarbsPer100g = 55.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2870),
                            FatPer100g = 2.0,
                            Name = "Yufka",
                            ProteinPer100g = 8.0,
                            SugarPer100g = 1.0
                        },
                        new
                        {
                            Id = 66,
                            CaloriesPer100g = 360.0,
                            CarbsPer100g = 73.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2872),
                            FatPer100g = 1.0,
                            Name = "İrmik",
                            ProteinPer100g = 10.0,
                            SugarPer100g = 1.0
                        },
                        new
                        {
                            Id = 67,
                            CaloriesPer100g = 370.0,
                            CarbsPer100g = 75.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2873),
                            FatPer100g = 1.0,
                            Name = "Tel Şehriye",
                            ProteinPer100g = 12.0,
                            SugarPer100g = 1.0
                        },
                        new
                        {
                            Id = 68,
                            CaloriesPer100g = 96.0,
                            CarbsPer100g = 21.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2875),
                            FatPer100g = 1.5,
                            Name = "Mısır (Taze/Süt)",
                            ProteinPer100g = 3.0,
                            SugarPer100g = 4.5
                        },
                        new
                        {
                            Id = 69,
                            CaloriesPer100g = 130.0,
                            CarbsPer100g = 23.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2876),
                            FatPer100g = 0.5,
                            Name = "Barbunya (Taze)",
                            ProteinPer100g = 9.0,
                            SugarPer100g = 2.0
                        },
                        new
                        {
                            Id = 70,
                            CaloriesPer100g = 33.0,
                            CarbsPer100g = 7.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2877),
                            FatPer100g = 0.20000000000000001,
                            Name = "Bamya (Çiğ)",
                            ProteinPer100g = 2.0,
                            SugarPer100g = 1.5
                        },
                        new
                        {
                            Id = 71,
                            CaloriesPer100g = 31.0,
                            CarbsPer100g = 7.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2878),
                            FatPer100g = 0.20000000000000001,
                            Name = "Yeşil Fasulye (Çiğ)",
                            ProteinPer100g = 1.8,
                            SugarPer100g = 3.0
                        },
                        new
                        {
                            Id = 72,
                            CaloriesPer100g = 81.0,
                            CarbsPer100g = 14.5,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2880),
                            FatPer100g = 0.40000000000000002,
                            Name = "Bezelye (Çiğ)",
                            ProteinPer100g = 5.4000000000000004,
                            SugarPer100g = 5.7000000000000002
                        },
                        new
                        {
                            Id = 73,
                            CaloriesPer100g = 574.0,
                            CarbsPer100g = 15.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2881),
                            FatPer100g = 49.0,
                            Name = "Kabak Çekirdeği",
                            ProteinPer100g = 30.0,
                            SugarPer100g = 1.3
                        },
                        new
                        {
                            Id = 74,
                            CaloriesPer100g = 560.0,
                            CarbsPer100g = 28.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2882),
                            FatPer100g = 45.0,
                            Name = "Antep Fıstığı",
                            ProteinPer100g = 20.0,
                            SugarPer100g = 7.7000000000000002
                        },
                        new
                        {
                            Id = 75,
                            CaloriesPer100g = 380.0,
                            CarbsPer100g = 58.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2883),
                            FatPer100g = 5.0,
                            Name = "Sarı Leblebi",
                            ProteinPer100g = 19.0,
                            SugarPer100g = 10.0
                        },
                        new
                        {
                            Id = 76,
                            CaloriesPer100g = 595.0,
                            CarbsPer100g = 21.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2884),
                            FatPer100g = 54.0,
                            Name = "Tahin",
                            ProteinPer100g = 17.0,
                            SugarPer100g = 0.5
                        },
                        new
                        {
                            Id = 77,
                            CaloriesPer100g = 240.0,
                            CarbsPer100g = 63.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2885),
                            FatPer100g = 0.5,
                            Name = "Kuru Kayısı",
                            ProteinPer100g = 3.0,
                            SugarPer100g = 53.0
                        },
                        new
                        {
                            Id = 78,
                            CaloriesPer100g = 250.0,
                            CarbsPer100g = 64.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2886),
                            FatPer100g = 1.0,
                            Name = "Kuru İncir",
                            ProteinPer100g = 3.0,
                            SugarPer100g = 48.0
                        },
                        new
                        {
                            Id = 79,
                            CaloriesPer100g = 300.0,
                            CarbsPer100g = 79.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2887),
                            FatPer100g = 0.5,
                            Name = "Kuru Üzüm",
                            ProteinPer100g = 3.0,
                            SugarPer100g = 59.0
                        },
                        new
                        {
                            Id = 80,
                            CaloriesPer100g = 280.0,
                            CarbsPer100g = 75.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2888),
                            FatPer100g = 0.40000000000000002,
                            Name = "Hurma (Medine)",
                            ProteinPer100g = 2.0,
                            SugarPer100g = 63.0
                        },
                        new
                        {
                            Id = 81,
                            CaloriesPer100g = 26.0,
                            CarbsPer100g = 6.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2889),
                            FatPer100g = 0.29999999999999999,
                            Name = "Kapya Biber",
                            ProteinPer100g = 1.0,
                            SugarPer100g = 4.2000000000000002
                        },
                        new
                        {
                            Id = 82,
                            CaloriesPer100g = 25.0,
                            CarbsPer100g = 6.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2890),
                            FatPer100g = 0.20000000000000001,
                            Name = "Patlıcan",
                            ProteinPer100g = 1.0,
                            SugarPer100g = 3.5
                        },
                        new
                        {
                            Id = 83,
                            CaloriesPer100g = 17.0,
                            CarbsPer100g = 3.1000000000000001,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2891),
                            FatPer100g = 0.29999999999999999,
                            Name = "Yeşil Kabak",
                            ProteinPer100g = 1.2,
                            SugarPer100g = 2.5
                        },
                        new
                        {
                            Id = 84,
                            CaloriesPer100g = 25.0,
                            CarbsPer100g = 5.7999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2893),
                            FatPer100g = 0.10000000000000001,
                            Name = "Beyaz Lahana",
                            ProteinPer100g = 1.3,
                            SugarPer100g = 3.2000000000000002
                        },
                        new
                        {
                            Id = 85,
                            CaloriesPer100g = 25.0,
                            CarbsPer100g = 5.0,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2894),
                            FatPer100g = 0.29999999999999999,
                            Name = "Karnabahar",
                            ProteinPer100g = 1.8999999999999999,
                            SugarPer100g = 1.8999999999999999
                        },
                        new
                        {
                            Id = 86,
                            CaloriesPer100g = 22.0,
                            CarbsPer100g = 3.2999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2895),
                            FatPer100g = 0.29999999999999999,
                            Name = "Kültür Mantarı",
                            ProteinPer100g = 3.1000000000000001,
                            SugarPer100g = 2.0
                        },
                        new
                        {
                            Id = 87,
                            CaloriesPer100g = 61.0,
                            CarbsPer100g = 14.199999999999999,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2896),
                            FatPer100g = 0.29999999999999999,
                            Name = "Pırasa",
                            ProteinPer100g = 1.5,
                            SugarPer100g = 3.8999999999999999
                        },
                        new
                        {
                            Id = 88,
                            CaloriesPer100g = 15.0,
                            CarbsPer100g = 2.8999999999999999,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2897),
                            FatPer100g = 0.20000000000000001,
                            Name = "Marul / Göbek",
                            ProteinPer100g = 1.3999999999999999,
                            SugarPer100g = 0.80000000000000004
                        },
                        new
                        {
                            Id = 89,
                            CaloriesPer100g = 36.0,
                            CarbsPer100g = 6.2999999999999998,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2898),
                            FatPer100g = 0.80000000000000004,
                            Name = "Maydanoz",
                            ProteinPer100g = 3.0,
                            SugarPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = 90,
                            CaloriesPer100g = 29.0,
                            CarbsPer100g = 9.3000000000000007,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 11, 42, 673, DateTimeKind.Local).AddTicks(2899),
                            FatPer100g = 0.29999999999999999,
                            Name = "Limon",
                            ProteinPer100g = 1.1000000000000001,
                            SugarPer100g = 2.5
                        });
                });

            modelBuilder.Entity("FitnessApp.Api.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<int?>("FoodId")
                        .HasColumnType("int");

                    b.Property<double?>("GramAmount")
                        .HasColumnType("float");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("Sugar")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FitnessApp.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GoalCalories")
                        .HasColumnType("int");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("TargetWeight")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessApp.Api.Models.Exercise", b =>
                {
                    b.HasOne("FitnessApp.Api.Models.User", "User")
                        .WithMany("Exercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Models.Meal", b =>
                {
                    b.HasOne("FitnessApp.Api.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId");

                    b.HasOne("FitnessApp.Api.Models.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Models.User", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
